# Generated by Django 3.1.5 on 2021-02-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20210131_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='lattitude',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
